/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarsIndexRouteImport } from './routes/cars/index'
import { Route as CarsIdRouteImport } from './routes/cars/$id'
import { Route as ApiCarsRouteImport } from './routes/api/cars'
import { Route as ApiCarsIdRouteImport } from './routes/api/cars.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsIndexRoute = CarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsIdRoute = CarsIdRouteImport.update({
  id: '/cars/$id',
  path: '/cars/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCarsRoute = ApiCarsRouteImport.update({
  id: '/api/cars',
  path: '/api/cars',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCarsIdRoute = ApiCarsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCarsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/stats': typeof StatsRoute
  '/wishlist': typeof WishlistRoute
  '/api/cars': typeof ApiCarsRouteWithChildren
  '/cars/$id': typeof CarsIdRoute
  '/cars/': typeof CarsIndexRoute
  '/api/cars/$id': typeof ApiCarsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/stats': typeof StatsRoute
  '/wishlist': typeof WishlistRoute
  '/api/cars': typeof ApiCarsRouteWithChildren
  '/cars/$id': typeof CarsIdRoute
  '/cars': typeof CarsIndexRoute
  '/api/cars/$id': typeof ApiCarsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/stats': typeof StatsRoute
  '/wishlist': typeof WishlistRoute
  '/api/cars': typeof ApiCarsRouteWithChildren
  '/cars/$id': typeof CarsIdRoute
  '/cars/': typeof CarsIndexRoute
  '/api/cars/$id': typeof ApiCarsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/favorites'
    | '/stats'
    | '/wishlist'
    | '/api/cars'
    | '/cars/$id'
    | '/cars/'
    | '/api/cars/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/favorites'
    | '/stats'
    | '/wishlist'
    | '/api/cars'
    | '/cars/$id'
    | '/cars'
    | '/api/cars/$id'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/favorites'
    | '/stats'
    | '/wishlist'
    | '/api/cars'
    | '/cars/$id'
    | '/cars/'
    | '/api/cars/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  FavoritesRoute: typeof FavoritesRoute
  StatsRoute: typeof StatsRoute
  WishlistRoute: typeof WishlistRoute
  ApiCarsRoute: typeof ApiCarsRouteWithChildren
  CarsIdRoute: typeof CarsIdRoute
  CarsIndexRoute: typeof CarsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/': {
      id: '/cars/'
      path: '/cars'
      fullPath: '/cars/'
      preLoaderRoute: typeof CarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$id': {
      id: '/cars/$id'
      path: '/cars/$id'
      fullPath: '/cars/$id'
      preLoaderRoute: typeof CarsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cars': {
      id: '/api/cars'
      path: '/api/cars'
      fullPath: '/api/cars'
      preLoaderRoute: typeof ApiCarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cars/$id': {
      id: '/api/cars/$id'
      path: '/$id'
      fullPath: '/api/cars/$id'
      preLoaderRoute: typeof ApiCarsIdRouteImport
      parentRoute: typeof ApiCarsRoute
    }
  }
}

interface ApiCarsRouteChildren {
  ApiCarsIdRoute: typeof ApiCarsIdRoute
}

const ApiCarsRouteChildren: ApiCarsRouteChildren = {
  ApiCarsIdRoute: ApiCarsIdRoute,
}

const ApiCarsRouteWithChildren =
  ApiCarsRoute._addFileChildren(ApiCarsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  FavoritesRoute: FavoritesRoute,
  StatsRoute: StatsRoute,
  WishlistRoute: WishlistRoute,
  ApiCarsRoute: ApiCarsRouteWithChildren,
  CarsIdRoute: CarsIdRoute,
  CarsIndexRoute: CarsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
